# Generated by Django 5.2.6 on 2025-09-09 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('cover', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='blogs', to='category.category')),
                ('tags', models.ManyToManyField(related_name='blogs', to='tag.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
