# Generated by Django 5.2.6 on 2025-09-23 05:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PN', 'pending'), ('CF', 'confirmed'), ('FN', 'finish')])),
                ('subject', models.CharField(editable=False, max_length=100)),
                ('detail', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='client.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
