# Generated by Django 5.2.6 on 2025-09-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PN', 'pending'), ('CF', 'confirmed'), ('FN', 'finish'), ('NT', 'Nothing')]),
        ),
    ]
